name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-windows:
    name: Prebuild Binaries for Windows x64
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: actions/checkout@v6
      - run: npm i
      - name: Prebuild Node
        run: >-
          npm run prebuild -- --strip --arch x64 -r node
          -t 22.0.0
          -t 24.0.0
          -t 26.0.0
      - name: Prebuild Electron
        run: >-
          npm run prebuild -- --strip --arch x64 -r electron
          -t 29.0.0
          -t 31.0.0
          -t 32.0.0
          -t 33.0.0
          -t 34.0.0
          -t 35.0.0
          -t 36.0.0
          -t 37.0.0
          -t 38.0.0
          -t 39.0.0
          -t 40.0.0
          -t 41.0.0
          -t 42.3.0
          -t 43.0.0

  prebuild-windows-32:
    name: Prebuild Binaries for Windows ia32
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: actions/checkout@v6
      - run: npm i
      - name: Prebuild Node
        run: >-
          npm run prebuild -- --strip --arch ia32 -r node
          -t 22.0.0
      - name: Prebuild Electron
        run: >-
          npm run prebuild -- --strip --arch ia32 -r electron
          -t 29.0.0
          -t 31.0.0
          -t 32.0.0
          -t 33.0.0
          -t 34.0.0
          -t 35.0.0
          -t 36.0.0
          -t 37.0.0
          -t 38.0.0
          -t 39.0.0
          -t 40.0.0
          -t 41.0.0
          -t 42.3.0
          -t 43.0.0
