name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-windows:
    name: Prebuild Binaries for Windows x64
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: actions/checkout@v6
      - run: npm i
      - name: Prebuild
        run: >-
          npm run prebuild -- --strip --arch x64
          -t 22.0.0 -r node
          -t 24.0.0 -r node
          -t 29.0.0-alpha.1 -r electron
          -t 31.0.0-alpha.1 -r electron
          -t 31.0.0-beta.7 -r electron
          -t 32.0.0-alpha.1 -r electron
          -t 33.0.0-alpha.1 -r electron
          -t 34.0.0-alpha.1 -r electron
          -t 35.0.0-alpha.1 -r electron
          -t 36.0.0-alpha.1 -r electron
          -t 37.0.0-alpha.1 -r electron
          -t 38.0.0-alpha.1 -r electron
          -t 39.0.0-alpha.1 -r electron
          -t 40.0.0-alpha.2 -r electron
          -t 41.0.0-alpha.1 -r electron

  prebuild-windows-32:
    name: Prebuild Binaries for Windows ia32
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - uses: actions/checkout@v6
      - run: npm i
      - name: Prebuild
        run: >-
          npm run prebuild -- --strip --arch ia32
          -t 22.0.0 -r node
          -t 24.0.0 -r node
          -t 29.0.0-alpha.1 -r electron
          -t 31.0.0-alpha.1 -r electron
          -t 31.0.0-beta.7 -r electron
          -t 32.0.0-alpha.1 -r electron
          -t 33.0.0-alpha.1 -r electron
          -t 34.0.0-alpha.1 -r electron
          -t 35.0.0-alpha.1 -r electron
          -t 36.0.0-alpha.1 -r electron
          -t 37.0.0-alpha.1 -r electron
          -t 38.0.0-alpha.1 -r electron
          -t 39.0.0-alpha.1 -r electron
          -t 40.0.0-alpha.2 -r electron
          -t 41.0.0-alpha.1 -r electron
