name: Prebuild Binaries

on:
  pull_request:

jobs:
  prebuild-windows:
    name: Prebuild Binaries for Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v1
      - run: npm i
      - name: Prebuild
        run: |
          npm run apply-patches
          npm run prebuild -- --strip --all --arch ia32
          npm run prebuild -- --strip --all --arch x64
